apiVersion: v1
kind: Service
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  selector:
    app: mrdevops
    type: Loadbalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200

